{{- if not .Values.upstream.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-s3-cache.secretName" . }}
  labels:
    {{- include "simple-s3-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.upstream.credentials.accessKeyKey }}: {{ .Values.upstream.credentials.accessKey | quote }}
  {{ .Values.upstream.credentials.secretKeyKey }}: {{ .Values.upstream.credentials.secretKey | quote }}
  {{- if .Values.upstream.credentials.sessionTokenEnabled }}
  {{ .Values.upstream.credentials.sessionTokenKey }}: {{ .Values.upstream.credentials.sessionToken | quote }}
  {{- end }}
{{- end }}
