{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "simple-s3-cache.fullname" . }}
  labels:
    {{- include "simple-s3-cache.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ include "simple-s3-cache.name" . }}
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - {{ .Release.Name }}
      - key: simple-s3-cache.elei.io/metrics
        operator: In
        values:
          - "true"
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
