topology: external-gateway

image:
  repository: ghcr.io/ekkuleivonen/simple-s3-cache
  tag: latest

gateway:
  replicaCount: 2
  externalPeers:
    - id: simple-s3-cache-0
      url: http://cache-0.storage.example.internal:8080
    - id: simple-s3-cache-1
      url: http://cache-1.storage.example.internal:8080
    - id: simple-s3-cache-2
      url: http://cache-2.storage.example.internal:8080
  service:
    type: LoadBalancer
    port: 9000

serviceMonitor:
  enabled: true

networkPolicy:
  enabled: true
  egress:
    allowDNS: true
    allowAll: true
